/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import { StorageZone } from '../../../services/connectionStorageService';
import { type EmulatorConfiguration } from '../../../utils/emulatorConfiguration';
import { type BaseClusterModel } from '../../models/BaseClusterModel';

/**
 * Cluster model for the Connections View.
 * Simple, clean, no Azure dependencies.
 *
 * This represents user-added connections that are stored in ConnectionStorageService.
 * These connections have a stable storageId that serves as their clusterId for caching.
 */
export interface ConnectionClusterModel extends BaseClusterModel {
    /**
     * Stable identifier in storage - THIS is what becomes clusterId.
     *
     * This is a UUID generated by ConnectionStorageService when the connection
     * is first saved. It remains stable even when the item moves between folders.
     */
    storageId: string;

    /**
     * The storage zone this connection physically lives in (`Clusters` or `Emulators`).
     *
     * Decouples zone routing from {@link emulatorConfiguration}: a local/emulator
     * connection can live in the `Clusters` zone (e.g. a migrated legacy connection) and
     * still keep its emulator TLS behaviour. Optional for back-compat — when absent,
     * callers fall back to the `isEmulator` inference via {@link resolveStorageZone}.
     */
    storageZone?: StorageZone;

    /**
     * Emulator configuration (optional).
     * Present when this connection represents a local emulator instance.
     */
    emulatorConfiguration?: EmulatorConfiguration;

    /**
     * The selected authentication method ID (e.g. 'NativeAuth', 'MicrosoftEntraID').
     * Populated from storage when the tree item is built, used for tooltip display.
     */
    selectedAuthMethod?: string;

    /**
     * The connection username for native (SCRAM) authentication.
     * Populated from storage when the tree item is built, used for tooltip display.
     * Never contains a password.
     */
    connectionUser?: string;
}

/**
 * Resolve the storage zone a connection lives in. Prefers the explicit
 * {@link ConnectionClusterModel.storageZone}; falls back to inferring it from
 * `emulatorConfiguration.isEmulator` for connections built before the field existed.
 *
 * Use this everywhere a connection operation must pick a storage zone, instead of the
 * legacy `emulatorConfiguration?.isEmulator ? Emulators : Clusters` inference — that
 * inference breaks for an emulator connection that has been moved into the `Clusters`
 * zone (it would be looked up in the wrong zone).
 */
export function resolveStorageZone(
    cluster: Pick<ConnectionClusterModel, 'storageZone' | 'emulatorConfiguration'>,
): StorageZone {
    if (cluster.storageZone) {
        return cluster.storageZone;
    }
    return cluster.emulatorConfiguration?.isEmulator ? StorageZone.Emulators : StorageZone.Clusters;
}
