/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import { type EmulatorConfiguration } from '../../../utils/emulatorConfiguration';
import { type BaseClusterModel } from '../../models/BaseClusterModel';

/**
 * Cluster model for the Connections View.
 * Simple, clean, no Azure dependencies.
 *
 * This represents user-added connections that are stored in ConnectionStorageService.
 * These connections have a stable storageId that serves as their clusterId for caching.
 */
export interface ConnectionClusterModel extends BaseClusterModel {
    /**
     * Stable identifier in storage - THIS is what becomes clusterId.
     *
     * This is a UUID generated by ConnectionStorageService when the connection
     * is first saved. It remains stable even when the item moves between folders.
     */
    storageId: string;

    /**
     * Emulator configuration (optional).
     * Present when this connection represents a local emulator instance.
     */
    emulatorConfiguration?: EmulatorConfiguration;

    /**
     * The selected authentication method ID (e.g. 'NativeAuth', 'MicrosoftEntraID').
     * Populated from storage when the tree item is built, used for tooltip display.
     */
    selectedAuthMethod?: string;

    /**
     * The connection username for native (SCRAM) authentication.
     * Populated from storage when the tree item is built, used for tooltip display.
     * Never contains a password.
     */
    connectionUser?: string;
}
