/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

// AUTO-GENERATED — DO NOT EDIT BY HAND
//
// Generated by: npm run generate  (scripts/generate-from-reference.ts)
// Source:       resources/scraped/index-reference.md
//
// To change index data, re-run the scraper (npm run scrape) then the generator.

import { type IndexReferenceEntry } from './types';

export const INDEX_TYPES: readonly IndexReferenceEntry[] = [
    { name: 'Single Field', description: 'Indexes a single field for faster lookups.', supported: true },
    { name: 'Compound', description: 'Indexes multiple fields in one index.', supported: true },
    { name: 'Multikey', description: 'Indexes array fields by indexing each element.', supported: true },
    { name: 'Text', description: 'Supports text search on string fields.', supported: true },
    { name: 'Wildcard', description: 'Dynamically indexes all or selected fields.', supported: true },
    { name: 'Geospatial', description: 'Supports spatial queries on GeoJSON data.', supported: true },
    { name: 'Hashed', description: 'Indexes hashed field values, often for sharding.', supported: true },
    { name: 'Vector', description: 'Enables similarity search on vector data.', supported: true },
];

export const INDEX_PROPERTIES: readonly IndexReferenceEntry[] = [
    {
        name: 'TTL',
        description: 'Automatically deletes documents after a specified time-to-live period.',
        supported: true,
    },
    { name: 'Unique', description: 'Ensures that all values in the indexed field are unique.', supported: true },
    {
        name: 'Partial',
        description: 'Indexes only documents that match a specified filter condition.',
        supported: true,
    },
    { name: 'Case Insensitive', description: 'Supports case-insensitive indexing for string fields.', supported: true },
    { name: 'Sparse', description: 'Indexes only documents that contain the indexed field.', supported: true },
    {
        name: 'Background',
        description: 'Allows the index to be created in the background without blocking operations.',
        supported: true,
    },
];
