/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

// AUTO-GENERATED — DO NOT EDIT BY HAND
//
// Generated by: npm run generate  (scripts/generate-from-reference.ts)
// Sources:      resources/operator-reference-scraped.md
//               resources/operator-reference-overrides.md
//
// To change operator data, edit the overrides file and re-run the generator.

import { getDocLink } from './docLinks';
import { registerOperators } from './getFilteredCompletions';
import { META_ACCUMULATOR } from './metaTags';
import { type OperatorEntry } from './types';

// ---------------------------------------------------------------------------
// Accumulators ($group, $bucket, $bucketAuto, $setWindowFields)
// ---------------------------------------------------------------------------

const groupAccumulators: readonly OperatorEntry[] = [
    {
        value: '$addToSet',
        meta: META_ACCUMULATOR,
        description:
            "The addToSet operator adds elements to an array if they don't already exist, while ensuring uniqueness of elements within the set.",
        snippet: '{ $addToSet: "${1:\\$field}" }',
        link: getDocLink('$addToSet', META_ACCUMULATOR),
    },
    {
        value: '$avg',
        meta: META_ACCUMULATOR,
        description: 'Computes the average of numeric values for documents in a group, bucket, or window.',
        snippet: '{ $avg: "${1:\\$field}" }',
        link: getDocLink('$avg', META_ACCUMULATOR),
    },
    {
        value: '$bottom',
        meta: META_ACCUMULATOR,
        description:
            "The $bottom operator returns the last document from the query's result set sorted by one or more fields",
        snippet: '{ $bottom: { sortBy: { ${1:field}: ${2:1} }, output: "${3:\\$field}" } }',
        link: getDocLink('$bottom', META_ACCUMULATOR),
    },
    {
        value: '$bottomN',
        meta: META_ACCUMULATOR,
        description: 'The $bottomN operator returns the last N documents from the result sorted by one or more fields',
        snippet: '{ $bottomN: { n: ${1:number}, sortBy: { ${2:field}: ${3:1} }, output: "${4:\\$field}" } }',
        link: getDocLink('$bottomN', META_ACCUMULATOR),
    },
    {
        value: '$count',
        meta: META_ACCUMULATOR,
        description:
            'The `$count` operator is used to count the number of documents that match a query filtering criteria.',
        snippet: '{ $count: {} }',
        link: getDocLink('$count', META_ACCUMULATOR),
    },
    {
        value: '$first',
        meta: META_ACCUMULATOR,
        description: "The $first operator returns the first value in a group according to the group's sorting order.",
        snippet: '{ $first: "${1:\\$field}" }',
        link: getDocLink('$first', META_ACCUMULATOR),
    },
    {
        value: '$firstN',
        meta: META_ACCUMULATOR,
        description:
            'The $firstN operator sorts documents on one or more fields specified by the query and returns the first N document matching the filtering criteria',
        snippet: '{ $firstN: { input: "${1:\\$field}", n: ${2:number} } }',
        link: getDocLink('$firstN', META_ACCUMULATOR),
    },
    {
        value: '$last',
        meta: META_ACCUMULATOR,
        description: 'The $last operator returns the last document from the result sorted by one or more fields',
        snippet: '{ $last: "${1:\\$field}" }',
        link: getDocLink('$last', META_ACCUMULATOR),
    },
    {
        value: '$lastN',
        meta: META_ACCUMULATOR,
        description: 'The $lastN accumulator operator returns the last N values in a group of documents.',
        snippet: '{ $lastN: { input: "${1:\\$field}", n: ${2:number} } }',
        link: getDocLink('$lastN', META_ACCUMULATOR),
    },
    {
        value: '$max',
        meta: META_ACCUMULATOR,
        description: 'The $max operator returns the maximum value from a set of input values.',
        snippet: '{ $max: "${1:\\$field}" }',
        link: getDocLink('$max', META_ACCUMULATOR),
    },
    {
        value: '$maxN',
        meta: META_ACCUMULATOR,
        description: 'Retrieves the top N values based on a specified filtering criteria',
        snippet: '{ $maxN: { input: "${1:\\$field}", n: ${2:number} } }',
        link: getDocLink('$maxN', META_ACCUMULATOR),
    },
    {
        value: '$median',
        meta: META_ACCUMULATOR,
        description: 'The $median operator calculates the median value of a numeric field in a group of documents.',
        snippet: '{ $median: { input: "${1:\\$field}", method: "approximate" } }',
        link: getDocLink('$median', META_ACCUMULATOR),
    },
    {
        value: '$mergeObjects',
        meta: META_ACCUMULATOR,
        description: 'The $mergeObjects operator merges multiple documents into a single document',
        snippet: '{ $mergeObjects: "${1:\\$field}" }',
        link: getDocLink('$mergeObjects', META_ACCUMULATOR),
    },
    {
        value: '$min',
        meta: META_ACCUMULATOR,
        description: 'Retrieves the minimum value for a specified field',
        snippet: '{ $min: "${1:\\$field}" }',
        link: getDocLink('$min', META_ACCUMULATOR),
    },
    {
        value: '$percentile',
        meta: META_ACCUMULATOR,
        description:
            'The $percentile operator calculates the percentile of numerical values that match a filtering criteria',
        snippet: '{ $percentile: { input: "${1:\\$field}", p: [${2:0.5}], method: "approximate" } }',
        link: getDocLink('$percentile', META_ACCUMULATOR),
    },
    {
        value: '$push',
        meta: META_ACCUMULATOR,
        description: 'The $push operator adds a specified value to an array within a document.',
        snippet: '{ $push: "${1:\\$field}" }',
        link: getDocLink('$push', META_ACCUMULATOR),
    },
    {
        value: '$stdDevPop',
        meta: META_ACCUMULATOR,
        description: 'The $stddevpop operator calculates the standard deviation of the specified values',
        snippet: '{ $stdDevPop: "${1:\\$field}" }',
        link: getDocLink('$stdDevPop', META_ACCUMULATOR),
    },
    {
        value: '$stdDevSamp',
        meta: META_ACCUMULATOR,
        description:
            'The $stddevsamp operator calculates the standard deviation of a specified sample of values and not the entire population',
        snippet: '{ $stdDevSamp: "${1:\\$field}" }',
        link: getDocLink('$stdDevSamp', META_ACCUMULATOR),
    },
    {
        value: '$sum',
        meta: META_ACCUMULATOR,
        description: 'The $sum operator calculates the sum of the values of a field based on a filtering criteria',
        snippet: '{ $sum: "${1:\\$field}" }',
        link: getDocLink('$sum', META_ACCUMULATOR),
    },
    {
        value: '$top',
        meta: META_ACCUMULATOR,
        description: 'The $top operator returns the first document from the result set sorted by one or more fields',
        snippet: '{ $top: { sortBy: { ${1:field}: ${2:1} }, output: "${3:\\$field}" } }',
        link: getDocLink('$top', META_ACCUMULATOR),
    },
    {
        value: '$topN',
        meta: META_ACCUMULATOR,
        description: 'The $topN operator returns the first N documents from the result sorted by one or more fields',
        snippet: '{ $topN: { n: ${1:number}, sortBy: { ${2:field}: ${3:1} }, output: "${4:\\$field}" } }',
        link: getDocLink('$topN', META_ACCUMULATOR),
    },
];

// ---------------------------------------------------------------------------
// Registration
// ---------------------------------------------------------------------------

registerOperators([...groupAccumulators]);
