/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

// AUTO-GENERATED — DO NOT EDIT BY HAND
//
// Generated by: npm run generate  (scripts/generate-from-reference.ts)
// Sources:      resources/operator-reference-scraped.md
//               resources/operator-reference-overrides.md
//
// To change operator data, edit the overrides file and re-run the generator.

import { getDocLink } from './docLinks';
import { registerOperators } from './getFilteredCompletions';
import {
    META_EXPR_ARITH,
    META_EXPR_ARRAY,
    META_EXPR_BITWISE,
    META_EXPR_BOOL,
    META_EXPR_COMPARISON,
    META_EXPR_CONDITIONAL,
    META_EXPR_DATASIZE,
    META_EXPR_DATE,
    META_EXPR_LITERAL,
    META_EXPR_MISC,
    META_EXPR_OBJECT,
    META_EXPR_SET,
    META_EXPR_STRING,
    META_EXPR_TIMESTAMP,
    META_EXPR_TRIG,
    META_EXPR_TYPE,
    META_EXPR_VARIABLE,
} from './metaTags';
import { type OperatorEntry } from './types';

// ---------------------------------------------------------------------------
// Arithmetic Expression Operators
// ---------------------------------------------------------------------------

const arithmeticExpressionOperators: readonly OperatorEntry[] = [
    {
        value: '$abs',
        meta: META_EXPR_ARITH,
        description: 'The $abs operator returns the absolute value of a number.',
        snippet: '{ $abs: "${1:\\$field}" }',
        link: getDocLink('$abs', META_EXPR_ARITH),
    },
    {
        value: '$add',
        meta: META_EXPR_ARITH,
        description: 'The $add operator returns the sum of two numbers or the sum of a date and numbers.',
        snippet: '{ $add: ["${1:\\$field1}", "${2:\\$field2}"] }',
        link: getDocLink('$add', META_EXPR_ARITH),
    },
    {
        value: '$ceil',
        meta: META_EXPR_ARITH,
        description: 'The $ceil operator returns the smallest integer greater than or equal to the specified number.',
        snippet: '{ $ceil: "${1:\\$field}" }',
        link: getDocLink('$ceil', META_EXPR_ARITH),
    },
    {
        value: '$divide',
        meta: META_EXPR_ARITH,
        description: 'The $divide operator divides two numbers and returns the quotient.',
        snippet: '{ $divide: ["${1:\\$field1}", "${2:\\$field2}"] }',
        link: getDocLink('$divide', META_EXPR_ARITH),
    },
    {
        value: '$exp',
        meta: META_EXPR_ARITH,
        description: 'The $exp operator raises e to the specified exponent and returns the result',
        snippet: '{ $exp: "${1:\\$field}" }',
        link: getDocLink('$exp', META_EXPR_ARITH),
    },
    {
        value: '$floor',
        meta: META_EXPR_ARITH,
        description: 'The $floor operator returns the largest integer less than or equal to the specified number',
        snippet: '{ $floor: "${1:\\$field}" }',
        link: getDocLink('$floor', META_EXPR_ARITH),
    },
    {
        value: '$ln',
        meta: META_EXPR_ARITH,
        description: 'The $ln operator calculates the natural logarithm of the input',
        snippet: '{ $ln: "${1:\\$field}" }',
        link: getDocLink('$ln', META_EXPR_ARITH),
    },
    {
        value: '$log',
        meta: META_EXPR_ARITH,
        description: 'The $log operator calculates the logarithm of a number in the specified base',
        snippet: '{ $log: ["${1:\\$number}", ${2:base}] }',
        link: getDocLink('$log', META_EXPR_ARITH),
    },
    {
        value: '$log10',
        meta: META_EXPR_ARITH,
        description: 'The $log10 operator calculates the log of a specified number in base 10',
        snippet: '{ $log10: "${1:\\$field}" }',
        link: getDocLink('$log10', META_EXPR_ARITH),
    },
    {
        value: '$mod',
        meta: META_EXPR_ARITH,
        description:
            'The $mod operator performs a modulo operation on the value of a field and selects documents with a specified result.',
        snippet: '{ $mod: ["${1:\\$field1}", "${2:\\$field2}"] }',
        link: 'https://learn.microsoft.com/en-us/azure/documentdb/operators/evaluation-query/$mod',
    },
    {
        value: '$multiply',
        meta: META_EXPR_ARITH,
        description: 'The $multiply operator multiplies the input numerical values',
        snippet: '{ $multiply: ["${1:\\$field1}", "${2:\\$field2}"] }',
        link: getDocLink('$multiply', META_EXPR_ARITH),
    },
    {
        value: '$pow',
        meta: META_EXPR_ARITH,
        description:
            'The `$pow` operator calculates the value of a numerical value raised to the power of a specified exponent.',
        snippet: '{ $pow: ["${1:\\$field1}", "${2:\\$field2}"] }',
        link: getDocLink('$pow', META_EXPR_ARITH),
    },
    {
        value: '$round',
        meta: META_EXPR_ARITH,
        description: 'The $round operator rounds a number to a specified decimal place.',
        snippet: '{ $round: ["${1:\\$field}", ${2:place}] }',
        link: getDocLink('$round', META_EXPR_ARITH),
    },
    {
        value: '$sqrt',
        meta: META_EXPR_ARITH,
        description: 'The $sqrt operator calculates and returns the square root of an input number',
        snippet: '{ $sqrt: "${1:\\$field}" }',
        link: getDocLink('$sqrt', META_EXPR_ARITH),
    },
    {
        value: '$subtract',
        meta: META_EXPR_ARITH,
        description: 'The $subtract operator subtracts two numbers and returns the result.',
        snippet: '{ $subtract: ["${1:\\$field1}", "${2:\\$field2}"] }',
        link: getDocLink('$subtract', META_EXPR_ARITH),
    },
    {
        value: '$trunc',
        meta: META_EXPR_ARITH,
        description: 'The $trunc operator truncates a number to a specified decimal place.',
        snippet: '{ $trunc: "${1:\\$field}" }',
        link: getDocLink('$trunc', META_EXPR_ARITH),
    },
];

// ---------------------------------------------------------------------------
// Array Expression Operators
// ---------------------------------------------------------------------------

const arrayExpressionOperators: readonly OperatorEntry[] = [
    {
        value: '$arrayElemAt',
        meta: META_EXPR_ARRAY,
        description: 'The $arrayElemAt returns the element at the specified array index.',
        snippet: '{ $arrayElemAt: ["${1:\\$array}", ${2:index}] }',
        link: getDocLink('$arrayElemAt', META_EXPR_ARRAY),
    },
    {
        value: '$arrayToObject',
        meta: META_EXPR_ARRAY,
        description: 'The $arrayToObject allows converting an array into a single document.',
        snippet: '{ $arrayToObject: "${1:\\$array}" }',
        link: getDocLink('$arrayToObject', META_EXPR_ARRAY),
    },
    {
        value: '$concatArrays',
        meta: META_EXPR_ARRAY,
        description: 'The $concatArrays is used to combine multiple arrays into a single array.',
        snippet: '{ $concatArrays: ["${1:\\$array1}", "${2:\\$array2}"] }',
        link: getDocLink('$concatArrays', META_EXPR_ARRAY),
    },
    {
        value: '$filter',
        meta: META_EXPR_ARRAY,
        description: 'The $filter operator filters for elements from an array based on a specified condition.',
        snippet: '{ $filter: { input: "${1:\\$array}", as: "${2:item}", cond: { ${3:expression} } } }',
        link: getDocLink('$filter', META_EXPR_ARRAY),
    },
    {
        value: '$firstN',
        meta: META_EXPR_ARRAY,
        description:
            'The $firstN operator sorts documents on one or more fields specified by the query and returns the first N document matching the filtering criteria',
        snippet: '{ $firstN: { input: "${1:\\$array}", n: ${2:number} } }',
        link: 'https://learn.microsoft.com/en-us/azure/documentdb/operators/accumulators/$firstn',
    },
    {
        value: '$in',
        meta: META_EXPR_ARRAY,
        description: 'The $in operator matches value of a field against an array of specified values',
        snippet: '{ $in: ["${1:\\$field}", "${2:\\$array}"] }',
        link: 'https://learn.microsoft.com/en-us/azure/documentdb/operators/comparison-query/$in',
    },
    {
        value: '$indexOfArray',
        meta: META_EXPR_ARRAY,
        description:
            'The $indexOfArray operator is used to search for an element in an array and return the index of the first occurrence of the element.',
        snippet: '{ $indexOfArray: ["${1:\\$array}", "${2:value}"] }',
        link: getDocLink('$indexOfArray', META_EXPR_ARRAY),
    },
    {
        value: '$isArray',
        meta: META_EXPR_ARRAY,
        description: 'The $isArray operator is used to determine if a specified value is an array.',
        snippet: '{ $isArray: "${1:\\$field}" }',
        link: getDocLink('$isArray', META_EXPR_ARRAY),
    },
    {
        value: '$lastN',
        meta: META_EXPR_ARRAY,
        description: 'The $lastN accumulator operator returns the last N values in a group of documents.',
        snippet: '{ $lastN: { input: "${1:\\$array}", n: ${2:number} } }',
        link: 'https://learn.microsoft.com/en-us/azure/documentdb/operators/accumulators/$lastn',
    },
    {
        value: '$map',
        meta: META_EXPR_ARRAY,
        description: 'The $map operator allows applying an expression to each element in an array.',
        snippet: '{ $map: { input: "${1:\\$array}", as: "${2:item}", in: { ${3:expression} } } }',
        link: getDocLink('$map', META_EXPR_ARRAY),
    },
    {
        value: '$maxN',
        meta: META_EXPR_ARRAY,
        description: 'Retrieves the top N values based on a specified filtering criteria',
        snippet: '{ $maxN: { input: "${1:\\$array}", n: ${2:number} } }',
        link: 'https://learn.microsoft.com/en-us/azure/documentdb/operators/accumulators/$maxn',
    },
    {
        value: '$minN',
        meta: META_EXPR_ARRAY,
        description: 'Retrieves the bottom N values based on a specified filtering criteria',
        snippet: '{ $minN: { input: "${1:\\$array}", n: ${2:number} } }',
        link: 'https://learn.microsoft.com/en-us/azure/documentdb/operators/accumulators/$minn',
    },
    {
        value: '$objectToArray',
        meta: META_EXPR_ARRAY,
        description: 'Converts an object into an array of key-value pair documents.',
        snippet: '{ $objectToArray: "${1:\\$object}" }',
    },
    {
        value: '$range',
        meta: META_EXPR_ARRAY,
        description: 'The $range operator allows generating an array of sequential integers.',
        snippet: '{ $range: [${1:start}, ${2:end}, ${3:step}] }',
        link: getDocLink('$range', META_EXPR_ARRAY),
    },
    {
        value: '$reduce',
        meta: META_EXPR_ARRAY,
        description:
            'The $reduce operator applies an expression to each element in an array & accumulate result as single value.',
        snippet: '{ $reduce: { input: "${1:\\$array}", initialValue: ${2:0}, in: { ${3:expression} } } }',
        link: getDocLink('$reduce', META_EXPR_ARRAY),
    },
    {
        value: '$reverseArray',
        meta: META_EXPR_ARRAY,
        description: 'The $reverseArray operator is used to reverse the order of elements in an array.',
        snippet: '{ $reverseArray: "${1:\\$array}" }',
        link: getDocLink('$reverseArray', META_EXPR_ARRAY),
    },
    {
        value: '$size',
        meta: META_EXPR_ARRAY,
        description:
            'The $size operator is used to query documents where an array field has a specified number of elements.',
        snippet: '{ $size: "${1:\\$array}" }',
        link: 'https://learn.microsoft.com/en-us/azure/documentdb/operators/array-query/$size',
    },
    {
        value: '$slice',
        meta: META_EXPR_ARRAY,
        description: 'The $slice operator returns a subset of an array from any element onwards in the array.',
        snippet: '{ $slice: ["${1:\\$array}", ${2:n}] }',
        link: getDocLink('$slice', META_EXPR_ARRAY),
    },
    {
        value: '$sortArray',
        meta: META_EXPR_ARRAY,
        description: 'The $sortArray operator helps in sorting the elements in an array.',
        snippet: '{ $sortArray: { input: "${1:\\$array}", sortBy: { ${2:field}: ${3:1} } } }',
        link: getDocLink('$sortArray', META_EXPR_ARRAY),
    },
    {
        value: '$zip',
        meta: META_EXPR_ARRAY,
        description: 'The $zip operator allows merging two or more arrays element-wise into a single array or arrays.',
        snippet: '{ $zip: { inputs: ["${1:\\$array1}", "${2:\\$array2}"] } }',
        link: getDocLink('$zip', META_EXPR_ARRAY),
    },
];

// ---------------------------------------------------------------------------
// Bitwise Operators
// ---------------------------------------------------------------------------

const bitwiseOperators: readonly OperatorEntry[] = [
    {
        value: '$bitAnd',
        meta: META_EXPR_BITWISE,
        description:
            'The $bitAnd operator performs a bitwise AND operation on integer values and returns the result as an integer.',
        snippet: '{ $bitAnd: [${1:value1}, ${2:value2}] }',
        link: getDocLink('$bitAnd', META_EXPR_BITWISE),
    },
    {
        value: '$bitNot',
        meta: META_EXPR_BITWISE,
        description:
            'The $bitNot operator performs a bitwise NOT operation on integer values and returns the result as an integer.',
        snippet: '{ $bitNot: "${1:\\$field}" }',
        link: getDocLink('$bitNot', META_EXPR_BITWISE),
    },
    {
        value: '$bitOr',
        meta: META_EXPR_BITWISE,
        description:
            'The $bitOr operator performs a bitwise OR operation on integer values and returns the result as an integer.',
        snippet: '{ $bitOr: [${1:value1}, ${2:value2}] }',
        link: getDocLink('$bitOr', META_EXPR_BITWISE),
    },
    {
        value: '$bitXor',
        meta: META_EXPR_BITWISE,
        description: 'The $bitXor operator performs a bitwise XOR operation on integer values.',
        snippet: '{ $bitXor: [${1:value1}, ${2:value2}] }',
        link: getDocLink('$bitXor', META_EXPR_BITWISE),
    },
];

// ---------------------------------------------------------------------------
// Boolean Expression Operators
// ---------------------------------------------------------------------------

const booleanExpressionOperators: readonly OperatorEntry[] = [
    {
        value: '$and',
        meta: META_EXPR_BOOL,
        description:
            'The $and operator joins multiple query clauses and returns documents that match all specified conditions.',
        snippet: '{ $and: ["${1:expression1}", "${2:expression2}"] }',
        link: getDocLink('$and', META_EXPR_BOOL),
    },
    {
        value: '$not',
        meta: META_EXPR_BOOL,
        description:
            "The $not operator performs a logical NOT operation on a specified expression, selecting documents that don't match the expression.",
        snippet: '{ $not: ["${1:expression}"] }',
        link: getDocLink('$not', META_EXPR_BOOL),
    },
    {
        value: '$or',
        meta: META_EXPR_BOOL,
        description:
            'The $or operator joins query clauses with a logical OR and returns documents that match at least one of the specified conditions.',
        snippet: '{ $or: ["${1:expression1}", "${2:expression2}"] }',
        link: getDocLink('$or', META_EXPR_BOOL),
    },
];

// ---------------------------------------------------------------------------
// Comparison Expression Operators
// ---------------------------------------------------------------------------

const comparisonExpressionOperators: readonly OperatorEntry[] = [
    {
        value: '$cmp',
        meta: META_EXPR_COMPARISON,
        description: 'The $cmp operator compares two values',
        snippet: '{ $cmp: ["${1:\\$field1}", "${2:\\$field2}"] }',
        link: getDocLink('$cmp', META_EXPR_COMPARISON),
    },
    {
        value: '$eq',
        meta: META_EXPR_COMPARISON,
        description: 'The $eq query operator compares the value of a field to a specified value',
        snippet: '{ $eq: ["${1:\\$field1}", "${2:\\$field2}"] }',
        link: getDocLink('$eq', META_EXPR_COMPARISON),
    },
    {
        value: '$gt',
        meta: META_EXPR_COMPARISON,
        description:
            'The $gt query operator retrieves documents where the value of a field is greater than a specified value',
        snippet: '{ $gt: ["${1:\\$field1}", "${2:\\$field2}"] }',
        link: getDocLink('$gt', META_EXPR_COMPARISON),
    },
    {
        value: '$gte',
        meta: META_EXPR_COMPARISON,
        description:
            'The $gte operator retrieves documents where the value of a field is greater than or equal to a specified value',
        snippet: '{ $gte: ["${1:\\$field1}", "${2:\\$field2}"] }',
        link: getDocLink('$gte', META_EXPR_COMPARISON),
    },
    {
        value: '$lt',
        meta: META_EXPR_COMPARISON,
        description: 'The $lt operator retrieves documents where the value of field is less than a specified value',
        snippet: '{ $lt: ["${1:\\$field1}", "${2:\\$field2}"] }',
        link: getDocLink('$lt', META_EXPR_COMPARISON),
    },
    {
        value: '$lte',
        meta: META_EXPR_COMPARISON,
        description:
            'The $lte operator retrieves documents where the value of a field is less than or equal to a specified value',
        snippet: '{ $lte: ["${1:\\$field1}", "${2:\\$field2}"] }',
        link: getDocLink('$lte', META_EXPR_COMPARISON),
    },
    {
        value: '$ne',
        meta: META_EXPR_COMPARISON,
        description: "The $ne operator retrieves documents where the value of a field doesn't equal a specified value",
        snippet: '{ $ne: ["${1:\\$field1}", "${2:\\$field2}"] }',
        link: getDocLink('$ne', META_EXPR_COMPARISON),
    },
];

// ---------------------------------------------------------------------------
// Data Size Operators
// ---------------------------------------------------------------------------

const dataSizeOperators: readonly OperatorEntry[] = [
    {
        value: '$bsonSize',
        meta: META_EXPR_DATASIZE,
        description: 'The $bsonSize operator returns the size of a document in bytes when encoded as BSON.',
        snippet: '{ $bsonSize: "${1:\\$field}" }',
        link: getDocLink('$bsonSize', META_EXPR_DATASIZE),
    },
    {
        value: '$binarySize',
        meta: META_EXPR_DATASIZE,
        description: 'The $binarySize operator is used to return the size of a binary data field.',
        snippet: '{ $binarySize: "${1:\\$field}" }',
        link: getDocLink('$binarySize', META_EXPR_DATASIZE),
    },
];

// ---------------------------------------------------------------------------
// Date Expression Operators
// ---------------------------------------------------------------------------

const dateExpressionOperators: readonly OperatorEntry[] = [
    {
        value: '$dateAdd',
        meta: META_EXPR_DATE,
        description: 'The $dateAdd operator adds a specified number of time units (day, hour, month etc) to a date.',
        snippet: '{ $dateAdd: { startDate: "${1:\\$dateField}", unit: "${2:day}", amount: ${3:1} } }',
        link: getDocLink('$dateAdd', META_EXPR_DATE),
    },
    {
        value: '$dateDiff',
        meta: META_EXPR_DATE,
        description:
            'The $dateDiff operator calculates the difference between two dates in various units such as years, months, days, etc.',
        snippet: '{ $dateDiff: { startDate: "${1:\\$startDate}", endDate: "${2:\\$endDate}", unit: "${3:day}" } }',
        link: getDocLink('$dateDiff', META_EXPR_DATE),
    },
    {
        value: '$dateFromParts',
        meta: META_EXPR_DATE,
        description: 'The $dateFromParts operator constructs a date from individual components.',
        snippet: '{ $dateFromParts: { year: ${1:2024}, month: ${2:1}, day: ${3:1} } }',
        link: getDocLink('$dateFromParts', META_EXPR_DATE),
    },
    {
        value: '$dateFromString',
        meta: META_EXPR_DATE,
        description: 'The $dateDiff operator converts a date/time string to a date object.',
        snippet: '{ $dateFromString: { dateString: "${1:dateString}" } }',
        link: getDocLink('$dateFromString', META_EXPR_DATE),
    },
    {
        value: '$dateSubtract',
        meta: META_EXPR_DATE,
        description: 'The $dateSubtract operator subtracts a specified amount of time from a date.',
        snippet: '{ $dateSubtract: { startDate: "${1:\\$dateField}", unit: "${2:day}", amount: ${3:1} } }',
        link: getDocLink('$dateSubtract', META_EXPR_DATE),
    },
    {
        value: '$dateToParts',
        meta: META_EXPR_DATE,
        description:
            'The $dateToParts operator decomposes a date into its individual parts such as year, month, day, and more.',
        snippet: '{ $dateToParts: { date: "${1:\\$dateField}" } }',
        link: getDocLink('$dateToParts', META_EXPR_DATE),
    },
    {
        value: '$dateToString',
        meta: META_EXPR_DATE,
        description: 'The $dateToString operator converts a date object into a formatted string.',
        snippet: '{ $dateToString: { format: "${1:%Y-%m-%d}", date: "${2:\\$dateField}" } }',
        link: getDocLink('$dateToString', META_EXPR_DATE),
    },
    {
        value: '$dateTrunc',
        meta: META_EXPR_DATE,
        description: 'The $dateTrunc operator truncates a date to a specified unit.',
        snippet: '{ $dateTrunc: { date: "${1:\\$dateField}", unit: "${2:day}" } }',
        link: getDocLink('$dateTrunc', META_EXPR_DATE),
    },
    {
        value: '$dayOfMonth',
        meta: META_EXPR_DATE,
        description: 'The $dayOfMonth operator extracts the day of the month from a date.',
        snippet: '{ $dayOfMonth: "${1:\\$dateField}" }',
        link: getDocLink('$dayOfMonth', META_EXPR_DATE),
    },
    {
        value: '$dayOfWeek',
        meta: META_EXPR_DATE,
        description: 'The $dayOfWeek operator extracts the day of the week from a date.',
        snippet: '{ $dayOfWeek: "${1:\\$dateField}" }',
        link: getDocLink('$dayOfWeek', META_EXPR_DATE),
    },
    {
        value: '$dayOfYear',
        meta: META_EXPR_DATE,
        description: 'The $dayOfYear operator extracts the day of the year from a date.',
        snippet: '{ $dayOfYear: "${1:\\$dateField}" }',
        link: getDocLink('$dayOfYear', META_EXPR_DATE),
    },
    {
        value: '$hour',
        meta: META_EXPR_DATE,
        description: 'The $hour operator returns the hour portion of a date as a number between 0 and 23.',
        snippet: '{ $hour: "${1:\\$dateField}" }',
        link: getDocLink('$hour', META_EXPR_DATE),
    },
    {
        value: '$isoDayOfWeek',
        meta: META_EXPR_DATE,
        description:
            'The $isoDayOfWeek operator returns the weekday number in ISO 8601 format, ranging from 1 (Monday) to 7 (Sunday).',
        snippet: '{ $isoDayOfWeek: "${1:\\$dateField}" }',
        link: getDocLink('$isoDayOfWeek', META_EXPR_DATE),
    },
    {
        value: '$isoWeek',
        meta: META_EXPR_DATE,
        description:
            'The $isoWeek operator returns the week number of the year in ISO 8601 format, ranging from 1 to 53.',
        snippet: '{ $isoWeek: "${1:\\$dateField}" }',
        link: getDocLink('$isoWeek', META_EXPR_DATE),
    },
    {
        value: '$isoWeekYear',
        meta: META_EXPR_DATE,
        description:
            'The $isoWeekYear operator returns the year number in ISO 8601 format, which can differ from the calendar year for dates at the beginning or end of the year.',
        snippet: '{ $isoWeekYear: "${1:\\$dateField}" }',
        link: getDocLink('$isoWeekYear', META_EXPR_DATE),
    },
    {
        value: '$millisecond',
        meta: META_EXPR_DATE,
        description: 'The $millisecond operator extracts the milliseconds portion from a date value.',
        snippet: '{ $millisecond: "${1:\\$dateField}" }',
        link: getDocLink('$millisecond', META_EXPR_DATE),
    },
    {
        value: '$minute',
        meta: META_EXPR_DATE,
        description: 'The $minute operator extracts the minute portion from a date value.',
        snippet: '{ $minute: "${1:\\$dateField}" }',
        link: getDocLink('$minute', META_EXPR_DATE),
    },
    {
        value: '$month',
        meta: META_EXPR_DATE,
        description: 'The $month operator extracts the month portion from a date value.',
        snippet: '{ $month: "${1:\\$dateField}" }',
        link: getDocLink('$month', META_EXPR_DATE),
    },
    {
        value: '$second',
        meta: META_EXPR_DATE,
        description: 'The $second operator extracts the seconds portion from a date value.',
        snippet: '{ $second: "${1:\\$dateField}" }',
        link: getDocLink('$second', META_EXPR_DATE),
    },
    {
        value: '$toDate',
        meta: META_EXPR_DATE,
        description: 'The $toDate operator converts supported types to a proper Date object.',
        snippet: '{ $toDate: "${1:\\$field}" }',
        link: 'https://learn.microsoft.com/en-us/azure/documentdb/operators/aggregation/type-expression/$todate',
    },
    {
        value: '$week',
        meta: META_EXPR_DATE,
        description: 'The $week operator returns the week number for a date as a value between 0 and 53.',
        snippet: '{ $week: "${1:\\$dateField}" }',
        link: getDocLink('$week', META_EXPR_DATE),
    },
    {
        value: '$year',
        meta: META_EXPR_DATE,
        description: 'The $year operator returns the year for a date as a four-digit number.',
        snippet: '{ $year: "${1:\\$dateField}" }',
        link: getDocLink('$year', META_EXPR_DATE),
    },
];

// ---------------------------------------------------------------------------
// Literal Expression Operator
// ---------------------------------------------------------------------------

const literalExpressionOperator: readonly OperatorEntry[] = [
    {
        value: '$literal',
        meta: META_EXPR_LITERAL,
        description:
            'The $literal operator returns the specified value without parsing it as an expression, allowing literal values to be used in aggregation pipelines.',
        snippet: '{ $literal: ${1:value} }',
        link: getDocLink('$literal', META_EXPR_LITERAL),
    },
];

// ---------------------------------------------------------------------------
// Miscellaneous Operators
// ---------------------------------------------------------------------------

const miscellaneousOperators: readonly OperatorEntry[] = [
    {
        value: '$getField',
        meta: META_EXPR_MISC,
        description: 'The $getField operator allows retrieving the value of a specified field from a document.',
        snippet: '{ $getField: { field: "${1:fieldName}", input: "${2:\\$object}" } }',
        link: getDocLink('$getField', META_EXPR_MISC),
    },
    {
        value: '$rand',
        meta: META_EXPR_MISC,
        description: 'The $rand operator generates a random float value between 0 and 1.',
        snippet: '{ $rand: {} }',
        link: 'https://learn.microsoft.com/en-us/azure/documentdb/operators/miscellaneous-query/$rand',
    },
    {
        value: '$sampleRate',
        meta: META_EXPR_MISC,
        description:
            'The $sampleRate operator randomly samples documents from a collection based on a specified probability rate, useful for statistical analysis and testing.',
        snippet: '{ $sampleRate: ${1:0.5} }',
        link: getDocLink('$sampleRate', META_EXPR_MISC),
    },
];

// ---------------------------------------------------------------------------
// Object Expression Operators
// ---------------------------------------------------------------------------

const objectExpressionOperators: readonly OperatorEntry[] = [
    {
        value: '$mergeObjects',
        meta: META_EXPR_OBJECT,
        description: 'The $mergeObjects operator merges multiple documents into a single document',
        snippet: '{ $mergeObjects: ["${1:\\$object1}", "${2:\\$object2}"] }',
        link: getDocLink('$mergeObjects', META_EXPR_OBJECT),
    },
    {
        value: '$objectToArray',
        meta: META_EXPR_OBJECT,
        description:
            'The objectToArray command is used to transform a document (object) into an array of key-value pairs.',
        snippet: '{ $objectToArray: "${1:\\$object}" }',
        link: getDocLink('$objectToArray', META_EXPR_OBJECT),
    },
    {
        value: '$setField',
        meta: META_EXPR_OBJECT,
        description: 'The setField command is used to add, update, or remove fields in embedded documents.',
        snippet: '{ $setField: { field: "${1:fieldName}", input: "${2:\\$object}", value: ${3:value} } }',
        link: getDocLink('$setField', META_EXPR_OBJECT),
    },
];

// ---------------------------------------------------------------------------
// Set Expression Operators
// ---------------------------------------------------------------------------

const setExpressionOperators: readonly OperatorEntry[] = [
    {
        value: '$allElementsTrue',
        meta: META_EXPR_SET,
        description: 'The $allElementsTrue operator returns true if all elements in an array evaluate to true.',
        snippet: '{ $allElementsTrue: ["${1:\\$array}"] }',
        link: getDocLink('$allElementsTrue', META_EXPR_SET),
    },
    {
        value: '$anyElementTrue',
        meta: META_EXPR_SET,
        description:
            'The $anyElementTrue operator returns true if any element in an array evaluates to a value of true.',
        snippet: '{ $anyElementTrue: ["${1:\\$array}"] }',
        link: getDocLink('$anyElementTrue', META_EXPR_SET),
    },
    {
        value: '$setDifference',
        meta: META_EXPR_SET,
        description:
            'The $setDifference operator returns a set with elements that exist in one set but not in a second set.',
        snippet: '{ $setDifference: ["${1:\\$set1}", "${2:\\$set2}"] }',
        link: getDocLink('$setDifference', META_EXPR_SET),
    },
    {
        value: '$setEquals',
        meta: META_EXPR_SET,
        description: 'The $setEquals operator returns true if two sets have the same distinct elements.',
        snippet: '{ $setEquals: ["${1:\\$set1}", "${2:\\$set2}"] }',
        link: getDocLink('$setEquals', META_EXPR_SET),
    },
    {
        value: '$setIntersection',
        meta: META_EXPR_SET,
        description: 'The $setIntersection operator returns the common elements that appear in all input arrays.',
        snippet: '{ $setIntersection: ["${1:\\$set1}", "${2:\\$set2}"] }',
        link: getDocLink('$setIntersection', META_EXPR_SET),
    },
    {
        value: '$setIsSubset',
        meta: META_EXPR_SET,
        description: 'The $setIsSubset operator determines if one array is a subset of a second array.',
        snippet: '{ $setIsSubset: ["${1:\\$set1}", "${2:\\$set2}"] }',
        link: getDocLink('$setIsSubset', META_EXPR_SET),
    },
    {
        value: '$setUnion',
        meta: META_EXPR_SET,
        description:
            'The $setUnion operator returns an array that contains all the unique elements from the input arrays.',
        snippet: '{ $setUnion: ["${1:\\$set1}", "${2:\\$set2}"] }',
        link: getDocLink('$setUnion', META_EXPR_SET),
    },
];

// ---------------------------------------------------------------------------
// String Expression Operators
// ---------------------------------------------------------------------------

const stringExpressionOperators: readonly OperatorEntry[] = [
    {
        value: '$concat',
        meta: META_EXPR_STRING,
        description: 'Concatenates two or more strings and returns the resulting string.',
        snippet: '{ $concat: ["${1:\\$string1}", "${2:\\$string2}"] }',
    },
    {
        value: '$dateFromString',
        meta: META_EXPR_STRING,
        description: 'The $dateDiff operator converts a date/time string to a date object.',
        snippet: '{ $dateFromString: "${1:\\$string}" }',
        link: 'https://learn.microsoft.com/en-us/azure/documentdb/operators/date-expression/$datefromstring',
    },
    {
        value: '$dateToString',
        meta: META_EXPR_STRING,
        description: 'The $dateToString operator converts a date object into a formatted string.',
        snippet: '{ $dateToString: "${1:\\$string}" }',
        link: 'https://learn.microsoft.com/en-us/azure/documentdb/operators/date-expression/$datetostring',
    },
    {
        value: '$indexOfBytes',
        meta: META_EXPR_STRING,
        description: 'Returns the byte index of the first occurrence of a substring within a string.',
        snippet: '{ $indexOfBytes: ["${1:\\$string}", "${2:substring}"] }',
    },
    {
        value: '$indexOfCP',
        meta: META_EXPR_STRING,
        description: 'Returns the code point index of the first occurrence of a substring within a string.',
        snippet: '{ $indexOfCP: ["${1:\\$string}", "${2:substring}"] }',
    },
    {
        value: '$ltrim',
        meta: META_EXPR_STRING,
        description: 'Removes whitespace or specified characters from the beginning of a string.',
        snippet: '{ $ltrim: { input: "${1:\\$string}" } }',
    },
    {
        value: '$regexFind',
        meta: META_EXPR_STRING,
        description: 'Applies a regular expression to a string and returns the first match.',
        snippet: '{ $regexFind: { input: "${1:\\$string}", regex: "${2:pattern}" } }',
    },
    {
        value: '$regexFindAll',
        meta: META_EXPR_STRING,
        description: 'Applies a regular expression to a string and returns all matches as an array.',
        snippet: '{ $regexFindAll: { input: "${1:\\$string}", regex: "${2:pattern}" } }',
    },
    {
        value: '$regexMatch',
        meta: META_EXPR_STRING,
        description: 'Applies a regular expression to a string and returns a boolean indicating if a match was found.',
        snippet: '{ $regexMatch: { input: "${1:\\$string}", regex: "${2:pattern}" } }',
    },
    {
        value: '$replaceOne',
        meta: META_EXPR_STRING,
        description: 'Replaces the first occurrence of a search string with a replacement string.',
        snippet: '{ $replaceOne: { input: "${1:\\$string}", find: "${2:find}", replacement: "${3:replacement}" } }',
    },
    {
        value: '$replaceAll',
        meta: META_EXPR_STRING,
        description: 'Replaces all occurrences of a search string with a replacement string.',
        snippet: '{ $replaceAll: { input: "${1:\\$string}", find: "${2:find}", replacement: "${3:replacement}" } }',
    },
    {
        value: '$rtrim',
        meta: META_EXPR_STRING,
        description: 'Removes whitespace or specified characters from the end of a string.',
        snippet: '{ $rtrim: { input: "${1:\\$string}" } }',
    },
    {
        value: '$split',
        meta: META_EXPR_STRING,
        description: 'Splits a string by a delimiter and returns an array of substrings.',
        snippet: '{ $split: ["${1:\\$string}", "${2:delimiter}"] }',
    },
    {
        value: '$strLenBytes',
        meta: META_EXPR_STRING,
        description: 'Returns the number of UTF-8 encoded bytes in the specified string.',
        snippet: '{ $strLenBytes: "${1:\\$string}" }',
    },
    {
        value: '$strLenCP',
        meta: META_EXPR_STRING,
        description: 'Returns the number of UTF-8 code points in the specified string.',
        snippet: '{ $strLenCP: "${1:\\$string}" }',
    },
    {
        value: '$strcasecmp',
        meta: META_EXPR_STRING,
        description: 'Performs a case-insensitive comparison of two strings and returns an integer.',
        snippet: '{ $strcasecmp: ["${1:\\$string1}", "${2:\\$string2}"] }',
    },
    {
        value: '$substr',
        meta: META_EXPR_STRING,
        description:
            'Returns a substring of a string, starting at a specified index for a specified length. Deprecated — use $substrBytes or $substrCP.',
        snippet: '{ $substr: ["${1:\\$string}", ${2:start}, ${3:length}] }',
    },
    {
        value: '$substrBytes',
        meta: META_EXPR_STRING,
        description:
            'Returns a substring of a string by byte index, starting at a specified index for a specified number of bytes.',
        snippet: '{ $substrBytes: ["${1:\\$string}", ${2:start}, ${3:length}] }',
    },
    {
        value: '$substrCP',
        meta: META_EXPR_STRING,
        description:
            'Returns a substring of a string by code point index, starting at a specified index for a specified number of code points.',
        snippet: '{ $substrCP: ["${1:\\$string}", ${2:start}, ${3:length}] }',
    },
    {
        value: '$toLower',
        meta: META_EXPR_STRING,
        description: 'Converts a string to lowercase and returns the result.',
        snippet: '{ $toLower: "${1:\\$string}" }',
    },
    {
        value: '$toString',
        meta: META_EXPR_STRING,
        description: 'The $toString operator converts an expression into a String',
        snippet: '{ $toString: "${1:\\$string}" }',
        link: 'https://learn.microsoft.com/en-us/azure/documentdb/operators/aggregation/type-expression/$tostring',
    },
    {
        value: '$trim',
        meta: META_EXPR_STRING,
        description: 'Removes whitespace or specified characters from both ends of a string.',
        snippet: '{ $trim: { input: "${1:\\$string}" } }',
    },
    {
        value: '$toUpper',
        meta: META_EXPR_STRING,
        description: 'Converts a string to uppercase and returns the result.',
        snippet: '{ $toUpper: "${1:\\$string}" }',
    },
];

// ---------------------------------------------------------------------------
// Timestamp Expression Operators
// ---------------------------------------------------------------------------

const timestampExpressionOperators: readonly OperatorEntry[] = [
    {
        value: '$tsIncrement',
        meta: META_EXPR_TIMESTAMP,
        description: 'The $tsIncrement operator extracts the increment portion from a timestamp value.',
        snippet: '{ $tsIncrement: "${1:\\$timestampField}" }',
        link: getDocLink('$tsIncrement', META_EXPR_TIMESTAMP),
    },
    {
        value: '$tsSecond',
        meta: META_EXPR_TIMESTAMP,
        description: 'The $tsSecond operator extracts the seconds portion from a timestamp value.',
        snippet: '{ $tsSecond: "${1:\\$timestampField}" }',
        link: getDocLink('$tsSecond', META_EXPR_TIMESTAMP),
    },
];

// ---------------------------------------------------------------------------
// Trigonometry Expression Operators
// ---------------------------------------------------------------------------

const trigonometryExpressionOperators: readonly OperatorEntry[] = [
    {
        value: '$sin',
        meta: META_EXPR_TRIG,
        description: 'Returns the sine of a value measured in radians.',
        snippet: '{ $sin: "${1:\\$value}" }',
    },
    {
        value: '$cos',
        meta: META_EXPR_TRIG,
        description: 'Returns the cosine of a value measured in radians.',
        snippet: '{ $cos: "${1:\\$value}" }',
    },
    {
        value: '$tan',
        meta: META_EXPR_TRIG,
        description: 'Returns the tangent of a value measured in radians.',
        snippet: '{ $tan: "${1:\\$value}" }',
    },
    {
        value: '$asin',
        meta: META_EXPR_TRIG,
        description: 'Returns the arcsine (inverse sine) of a value in radians.',
        snippet: '{ $asin: "${1:\\$value}" }',
    },
    {
        value: '$acos',
        meta: META_EXPR_TRIG,
        description: 'Returns the arccosine (inverse cosine) of a value in radians.',
        snippet: '{ $acos: "${1:\\$value}" }',
    },
    {
        value: '$atan',
        meta: META_EXPR_TRIG,
        description: 'Returns the arctangent (inverse tangent) of a value in radians.',
        snippet: '{ $atan: "${1:\\$value}" }',
    },
    {
        value: '$atan2',
        meta: META_EXPR_TRIG,
        description: 'Returns the arctangent of the quotient of two values, using the signs to determine the quadrant.',
        snippet: '{ $atan2: "${1:\\$value}" }',
    },
    {
        value: '$asinh',
        meta: META_EXPR_TRIG,
        description: 'Returns the inverse hyperbolic sine of a value.',
        snippet: '{ $asinh: "${1:\\$value}" }',
    },
    {
        value: '$acosh',
        meta: META_EXPR_TRIG,
        description: 'Returns the inverse hyperbolic cosine of a value.',
        snippet: '{ $acosh: "${1:\\$value}" }',
    },
    {
        value: '$atanh',
        meta: META_EXPR_TRIG,
        description: 'Returns the inverse hyperbolic tangent of a value.',
        snippet: '{ $atanh: "${1:\\$value}" }',
    },
    {
        value: '$sinh',
        meta: META_EXPR_TRIG,
        description: 'Returns the hyperbolic sine of a value.',
        snippet: '{ $sinh: "${1:\\$value}" }',
    },
    {
        value: '$cosh',
        meta: META_EXPR_TRIG,
        description: 'Returns the hyperbolic cosine of a value.',
        snippet: '{ $cosh: "${1:\\$value}" }',
    },
    {
        value: '$tanh',
        meta: META_EXPR_TRIG,
        description: 'Returns the hyperbolic tangent of a value.',
        snippet: '{ $tanh: "${1:\\$value}" }',
    },
    {
        value: '$degreesToRadians',
        meta: META_EXPR_TRIG,
        description: 'Converts a value from degrees to radians.',
        snippet: '{ $degreesToRadians: "${1:\\$angle}" }',
    },
    {
        value: '$radiansToDegrees',
        meta: META_EXPR_TRIG,
        description: 'Converts a value from radians to degrees.',
        snippet: '{ $radiansToDegrees: "${1:\\$angle}" }',
    },
];

// ---------------------------------------------------------------------------
// Type Expression Operators
// ---------------------------------------------------------------------------

const typeExpressionOperators: readonly OperatorEntry[] = [
    {
        value: '$convert',
        meta: META_EXPR_TYPE,
        description: 'The $convert operator converts an expression into the specified type',
        snippet: '{ $convert: { input: "${1:\\$field}", to: "${2:type}" } }',
        link: getDocLink('$convert', META_EXPR_TYPE),
    },
    {
        value: '$isNumber',
        meta: META_EXPR_TYPE,
        description: 'The $isNumber operator checks if a specified expression is a numerical type',
        snippet: '{ $isNumber: "${1:\\$field}" }',
        link: getDocLink('$isNumber', META_EXPR_TYPE),
    },
    {
        value: '$toBool',
        meta: META_EXPR_TYPE,
        description: 'The $toBool operator converts an expression into a Boolean type',
        snippet: '{ $toBool: "${1:\\$field}" }',
        link: getDocLink('$toBool', META_EXPR_TYPE),
    },
    {
        value: '$toDate',
        meta: META_EXPR_TYPE,
        description: 'The $toDate operator converts supported types to a proper Date object.',
        snippet: '{ $toDate: "${1:\\$field}" }',
        link: getDocLink('$toDate', META_EXPR_TYPE),
    },
    {
        value: '$toDecimal',
        meta: META_EXPR_TYPE,
        description: 'The $toDecimal operator converts an expression into a Decimal type',
        snippet: '{ $toDecimal: "${1:\\$field}" }',
        link: getDocLink('$toDecimal', META_EXPR_TYPE),
    },
    {
        value: '$toDouble',
        meta: META_EXPR_TYPE,
        description: 'The $toDouble operator converts an expression into a Double value',
        snippet: '{ $toDouble: "${1:\\$field}" }',
        link: getDocLink('$toDouble', META_EXPR_TYPE),
    },
    {
        value: '$toInt',
        meta: META_EXPR_TYPE,
        description: 'The $toInt operator converts an expression into an Integer',
        snippet: '{ $toInt: "${1:\\$field}" }',
        link: getDocLink('$toInt', META_EXPR_TYPE),
    },
    {
        value: '$toLong',
        meta: META_EXPR_TYPE,
        description: 'The $toLong operator converts an expression into a Long value',
        snippet: '{ $toLong: "${1:\\$field}" }',
        link: getDocLink('$toLong', META_EXPR_TYPE),
    },
    {
        value: '$toObjectId',
        meta: META_EXPR_TYPE,
        description: 'The $toObjectId operator converts an expression into an ObjectId',
        snippet: '{ $toObjectId: "${1:\\$field}" }',
        link: getDocLink('$toObjectId', META_EXPR_TYPE),
    },
    {
        value: '$toString',
        meta: META_EXPR_TYPE,
        description: 'The $toString operator converts an expression into a String',
        snippet: '{ $toString: "${1:\\$field}" }',
        link: getDocLink('$toString', META_EXPR_TYPE),
    },
    {
        value: '$type',
        meta: META_EXPR_TYPE,
        description: 'The $type operator retrieves documents if the chosen field is of the specified type.',
        snippet: '{ $type: "${1:\\$field}" }',
        link: 'https://learn.microsoft.com/en-us/azure/documentdb/operators/element-query/$type',
    },
];

// ---------------------------------------------------------------------------
// Variable Expression Operators
// ---------------------------------------------------------------------------

const variableExpressionOperators: readonly OperatorEntry[] = [
    {
        value: '$let',
        meta: META_EXPR_VARIABLE,
        description:
            'The $let operator allows defining variables for use in a specified expression, enabling complex calculations and reducing code repetition.',
        snippet: '{ $let: { vars: { ${1:var}: ${2:expression} }, in: ${3:expression} } }',
        link: getDocLink('$let', META_EXPR_VARIABLE),
    },
];

// ---------------------------------------------------------------------------
// Conditional Expression Operators
// ---------------------------------------------------------------------------

const conditionalExpressionOperators: readonly OperatorEntry[] = [
    {
        value: '$cond',
        meta: META_EXPR_CONDITIONAL,
        description:
            'The $cond operator is used to evaluate a condition and return one of two expressions based on the result.',
        snippet: '{ $cond: { if: { ${1:expression} }, then: ${2:trueValue}, else: ${3:falseValue} } }',
        link: getDocLink('$cond', META_EXPR_CONDITIONAL),
    },
    {
        value: '$ifNull',
        meta: META_EXPR_CONDITIONAL,
        description:
            'The $ifNull operator is used to evaluate an expression and return a specified value if the expression resolves to null.',
        snippet: '{ $ifNull: ["${1:\\$field}", ${2:replacement}] }',
        link: getDocLink('$ifNull', META_EXPR_CONDITIONAL),
    },
    {
        value: '$switch',
        meta: META_EXPR_CONDITIONAL,
        description:
            'The $switch operator is used to evaluate a series of conditions and return a value based on the first condition that evaluates to true.',
        snippet:
            '{ $switch: { branches: [{ case: { ${1:expression} }, then: ${2:value} }], default: ${3:defaultValue} } }',
        link: getDocLink('$switch', META_EXPR_CONDITIONAL),
    },
];

// ---------------------------------------------------------------------------
// Registration
// ---------------------------------------------------------------------------

registerOperators([
    ...arithmeticExpressionOperators,
    ...arrayExpressionOperators,
    ...bitwiseOperators,
    ...booleanExpressionOperators,
    ...comparisonExpressionOperators,
    ...dataSizeOperators,
    ...dateExpressionOperators,
    ...literalExpressionOperator,
    ...miscellaneousOperators,
    ...objectExpressionOperators,
    ...setExpressionOperators,
    ...stringExpressionOperators,
    ...timestampExpressionOperators,
    ...trigonometryExpressionOperators,
    ...typeExpressionOperators,
    ...variableExpressionOperators,
    ...conditionalExpressionOperators,
]);
