/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

// AUTO-GENERATED — DO NOT EDIT BY HAND
//
// Generated by: npm run generate  (scripts/generate-from-reference.ts)
// Sources:      resources/scraped/operator-reference.md
//               resources/overrides/operator-overrides.md
//               resources/overrides/operator-snippets.md
//
// To change operator data, edit the overrides/snippets files and re-run the generator.

import { getDocLink } from './docLinks';
import { registerOperators } from './getFilteredCompletions';
import { META_STAGE } from './metaTags';
import { type OperatorEntry } from './types';

// ---------------------------------------------------------------------------
// Aggregation Pipeline Stages
// ---------------------------------------------------------------------------

const aggregationPipelineStages: readonly OperatorEntry[] = [
    {
        value: '$addFields',
        meta: META_STAGE,
        description: 'The $addFields stage in the aggregation pipeline is used to add new fields to documents.',
        snippet: '{ $addFields: { ${1:newField}: ${2:expression} } }',
        link: getDocLink('$addFields', META_STAGE),
    },
    {
        value: '$bucket',
        meta: META_STAGE,
        description: 'Groups input documents into buckets based on specified boundaries.',
        snippet: '{ $bucket: { groupBy: "${1:\\$field}", boundaries: [${2:values}], default: "${3:Other}" } }',
        link: getDocLink('$bucket', META_STAGE),
    },
    {
        value: '$bucketAuto',
        meta: META_STAGE,
        description:
            'Categorizes documents into a specified number of groups based on a given expression, automatically determining bucket boundaries.',
        snippet: '{ $bucketAuto: { groupBy: "${1:\\$field}", buckets: ${2:number} } }',
    },
    {
        value: '$changeStream',
        meta: META_STAGE,
        description: 'The $changeStream stage opens a change stream cursor to track data changes in real-time.',
        snippet: '{ $changeStream: {} }',
        link: getDocLink('$changeStream', META_STAGE),
    },
    {
        value: '$collStats',
        meta: META_STAGE,
        description:
            'The $collStats stage in the aggregation pipeline is used to return statistics about a collection.',
        snippet: '{ $collStats: { storageStats: {} } }',
        link: getDocLink('$collStats', META_STAGE),
    },
    {
        value: '$count',
        meta: META_STAGE,
        description:
            'The `$count` operator is used to count the number of documents that match a query filtering criteria.',
        snippet: '{ $count: "${1:countField}" }',
        link: 'https://learn.microsoft.com/en-us/azure/documentdb/operators/accumulators/$count', // inferred from another category
    },
    {
        value: '$densify',
        meta: META_STAGE,
        description: 'Adds missing data points in a sequence of values within an array or collection.',
        snippet: '{ $densify: { field: "${1:field}", range: { step: ${2:1}, bounds: "full" } } }',
        link: getDocLink('$densify', META_STAGE),
    },
    {
        value: '$documents',
        meta: META_STAGE,
        description: 'The $documents stage creates a pipeline from a set of provided documents.',
        snippet: '{ $documents: [${1:documents}] }',
        link: getDocLink('$documents', META_STAGE),
    },
    {
        value: '$facet',
        meta: META_STAGE,
        description:
            'The $facet allows for multiple parallel aggregations to be executed within a single pipeline stage.',
        snippet: '{ $facet: { ${1:outputField}: [{ ${2:stage} }] } }',
        link: getDocLink('$facet', META_STAGE),
    },
    {
        value: '$fill',
        meta: META_STAGE,
        description:
            'The $fill stage allows filling missing values in documents based on specified methods and criteria.',
        snippet: '{ $fill: { output: { ${1:field}: { method: "${2:linear}" } } } }',
        link: getDocLink('$fill', META_STAGE),
    },
    {
        value: '$geoNear',
        meta: META_STAGE,
        description:
            'The $geoNear operator finds and sorts documents by their proximity to a geospatial point, returning distance information for each document.',
        snippet:
            '{ $geoNear: { near: { type: "Point", coordinates: [${1:lng}, ${2:lat}] }, distanceField: "${3:distance}" } }',
        link: getDocLink('$geoNear', META_STAGE),
    },
    {
        value: '$graphLookup',
        meta: META_STAGE,
        description:
            'Performs a recursive search on a collection to return documents connected by a specified field relationship.',
        snippet:
            '{ $graphLookup: { from: "${1:collection}", startWith: "${2:\\$field}", connectFromField: "${3:field}", connectToField: "${4:field}", as: "${5:result}" } }',
    },
    {
        value: '$group',
        meta: META_STAGE,
        description:
            'The $group stage groups documents by specified identifier expressions and applies accumulator expressions.',
        snippet: '{ $group: { _id: "${1:\\$field}", ${2:accumulator}: { ${3:\\$sum}: 1 } } }',
        link: getDocLink('$group', META_STAGE),
    },
    {
        value: '$indexStats',
        meta: META_STAGE,
        description: 'The $indexStats stage returns usage statistics for each index in the collection.',
        snippet: '{ $indexStats: {} }',
        link: getDocLink('$indexStats', META_STAGE),
    },
    {
        value: '$limit',
        meta: META_STAGE,
        description: 'Restricts the number of documents passed to the next stage in the pipeline.',
        snippet: '{ $limit: ${1:number} }',
    },
    {
        value: '$lookup',
        meta: META_STAGE,
        description:
            'The $lookup stage in the Aggregation Framework is used to perform left outer joins with other collections.',
        snippet:
            '{ $lookup: { from: "${1:collection}", localField: "${2:field}", foreignField: "${3:field}", as: "${4:result}" } }',
        link: getDocLink('$lookup', META_STAGE),
    },
    {
        value: '$match',
        meta: META_STAGE,
        description:
            'The $match stage in the aggregation pipeline is used to filter documents that match a specified condition.',
        snippet: '{ $match: { ${1:query} } }',
        link: getDocLink('$match', META_STAGE),
    },
    {
        value: '$merge',
        meta: META_STAGE,
        description:
            'The $merge stage in an aggregation pipeline writes the results of the aggregation to a specified collection.',
        snippet: '{ $merge: { into: "${1:collection}" } }',
        link: getDocLink('$merge', META_STAGE),
    },
    {
        value: '$out',
        meta: META_STAGE,
        description:
            'The `$out` stage in an aggregation pipeline writes the resulting documents to a specified collection.',
        snippet: '{ $out: "${1:collection}" }',
        link: getDocLink('$out', META_STAGE),
    },
    {
        value: '$project',
        meta: META_STAGE,
        description: 'Reshapes documents by including, excluding, or computing new fields.',
        snippet: '{ $project: { ${1:field}: 1 } }',
    },
    {
        value: '$redact',
        meta: META_STAGE,
        description: 'Filters the content of the documents based on access rights.',
        snippet:
            '{ $redact: { \\$cond: { if: { ${1:expression} }, then: "${2:\\$\\$DESCEND}", else: "${3:\\$\\$PRUNE}" } } }',
        link: getDocLink('$redact', META_STAGE),
    },
    {
        value: '$replaceRoot',
        meta: META_STAGE,
        description: 'Replaces the input document with a specified embedded document, promoting it to the top level.',
        snippet: '{ $replaceRoot: { newRoot: "${1:\\$field}" } }',
    },
    {
        value: '$replaceWith',
        meta: META_STAGE,
        description:
            'The $replaceWith operator in Azure DocumentDB returns a document after replacing a document with the specified document',
        snippet: '{ $replaceWith: "${1:\\$field}" }',
        link: getDocLink('$replaceWith', META_STAGE),
    },
    {
        value: '$sample',
        meta: META_STAGE,
        description: 'The $sample operator in Azure DocumentDB returns a randomly selected number of documents',
        snippet: '{ $sample: { size: ${1:number} } }',
        link: getDocLink('$sample', META_STAGE),
    },
    {
        value: '$search',
        meta: META_STAGE,
        description: 'Performs full-text search on string fields using Atlas Search or compatible search indexes.',
        snippet: '{ $search: { ${1} } }',
    },
    {
        value: '$searchMeta',
        meta: META_STAGE,
        description: 'Returns metadata about an Atlas Search query without returning the matching documents.',
        snippet: '{ $searchMeta: { ${1} } }',
    },
    {
        value: '$set',
        meta: META_STAGE,
        description: 'The $set operator in Azure DocumentDB updates or creates a new field with a specified value',
        snippet: '{ $set: { ${1:field}: ${2:expression} } }',
        link: getDocLink('$set', META_STAGE),
    },
    {
        value: '$setWindowFields',
        meta: META_STAGE,
        description:
            'Adds computed fields to documents using window functions over a specified partition and sort order.',
        snippet:
            '{ $setWindowFields: { partitionBy: "${1:\\$field}", sortBy: { ${2:field}: ${3:1} }, output: { ${4:newField}: { ${5:windowFunc} } } } }',
    },
    {
        value: '$skip',
        meta: META_STAGE,
        description:
            'The $skip stage in the aggregation pipeline is used to skip a specified number of documents from the input and pass the remaining documents to the next stage in the pipeline.',
        snippet: '{ $skip: ${1:number} }',
        link: getDocLink('$skip', META_STAGE),
    },
    {
        value: '$sort',
        meta: META_STAGE,
        description:
            'The $sort stage in the aggregation pipeline is used to order the documents in the pipeline by a specified field or fields.',
        snippet: '{ $sort: { ${1:field}: ${2:1} } }',
        link: getDocLink('$sort', META_STAGE),
    },
    {
        value: '$sortByCount',
        meta: META_STAGE,
        description:
            'The $sortByCount stage in the aggregation pipeline is used to group documents by a specified expression and then sort the count of documents in each group in descending order.',
        snippet: '{ $sortByCount: "${1:\\$field}" }',
        link: getDocLink('$sortByCount', META_STAGE),
    },
    {
        value: '$unionWith',
        meta: META_STAGE,
        description: 'Combines the results of two collections into a single result set, similar to SQL UNION ALL.',
        snippet: '{ $unionWith: { coll: "${1:collection}", pipeline: [${2}] } }',
    },
    {
        value: '$unset',
        meta: META_STAGE,
        description: 'The $unset stage in the aggregation pipeline is used to remove specified fields from documents.',
        snippet: '{ $unset: "${1:field}" }',
        link: getDocLink('$unset', META_STAGE),
    },
    {
        value: '$unwind',
        meta: META_STAGE,
        description:
            'The $unwind stage in the aggregation framework is used to deconstruct an array field from the input documents to output a document for each element.',
        snippet: '{ $unwind: "${1:\\$arrayField}" }',
        link: getDocLink('$unwind', META_STAGE),
    },
    {
        value: '$currentOp',
        meta: META_STAGE,
        description: 'Returns information on active and queued operations for the database instance.',
        snippet: '{ $currentOp: { allUsers: true } }',
    },
];

// ---------------------------------------------------------------------------
// Registration
// ---------------------------------------------------------------------------

registerOperators([...aggregationPipelineStages]);
