/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

// AUTO-GENERATED — DO NOT EDIT BY HAND
//
// Generated by: npm run generate  (scripts/generate-from-reference.ts)
// Sources:      resources/operator-reference-scraped.md
//               resources/operator-reference-overrides.md
//
// To change operator data, edit the overrides file and re-run the generator.

import { getDocLink } from './docLinks';
import { registerOperators } from './getFilteredCompletions';
import { META_VARIABLE } from './metaTags';
import { type OperatorEntry } from './types';

// ---------------------------------------------------------------------------
// Variables in Aggregation Expressions
// ---------------------------------------------------------------------------

const systemVariables: readonly OperatorEntry[] = [
    {
        value: '$$NOW',
        meta: META_VARIABLE,
        description:
            'Returns the current datetime as a Date object. Constant throughout a single aggregation pipeline.',
        link: getDocLink('$$NOW', META_VARIABLE),
    },
    {
        value: '$$ROOT',
        meta: META_VARIABLE,
        description:
            'References the root document — the top-level document currently being processed in the pipeline stage.',
        link: getDocLink('$$ROOT', META_VARIABLE),
    },
    {
        value: '$$REMOVE',
        meta: META_VARIABLE,
        description:
            'Removes a field from the output document. Used with $project or $addFields to conditionally exclude fields.',
        link: getDocLink('$$REMOVE', META_VARIABLE),
    },
    {
        value: '$$CURRENT',
        meta: META_VARIABLE,
        description:
            'References the current document in the pipeline stage. Equivalent to $$ROOT at the start of the pipeline.',
        link: getDocLink('$$CURRENT', META_VARIABLE),
    },
    {
        value: '$$DESCEND',
        meta: META_VARIABLE,
        description:
            'Used with $redact. Returns the document fields at the current level and continues descending into subdocuments.',
        link: getDocLink('$$DESCEND', META_VARIABLE),
    },
    {
        value: '$$PRUNE',
        meta: META_VARIABLE,
        description:
            'Used with $redact. Excludes all fields at the current document level and stops descending into subdocuments.',
        link: getDocLink('$$PRUNE', META_VARIABLE),
    },
    {
        value: '$$KEEP',
        meta: META_VARIABLE,
        description:
            'Used with $redact. Keeps all fields at the current document level without further descending into subdocuments.',
        link: getDocLink('$$KEEP', META_VARIABLE),
    },
];

// ---------------------------------------------------------------------------
// Registration
// ---------------------------------------------------------------------------

registerOperators([...systemVariables]);
