/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

// AUTO-GENERATED — DO NOT EDIT BY HAND
//
// Generated by: npm run generate  (scripts/generate-from-reference.ts)
// Sources:      resources/operator-reference-scraped.md
//               resources/operator-reference-overrides.md
//
// To change operator data, edit the overrides file and re-run the generator.

import { getDocLink } from './docLinks';
import { registerOperators } from './getFilteredCompletions';
import { META_UPDATE_ARRAY, META_UPDATE_BITWISE, META_UPDATE_FIELD } from './metaTags';
import { type OperatorEntry } from './types';

// ---------------------------------------------------------------------------
// Field Update Operators
// ---------------------------------------------------------------------------

const fieldUpdateOperators: readonly OperatorEntry[] = [
    {
        value: '$currentDate',
        meta: META_UPDATE_FIELD,
        description:
            'The $currentDate operator sets the value of a field to the current date, either as a Date or a timestamp.',
        snippet: '{ $currentDate: { "${1:field}": true } }',
        link: getDocLink('$currentDate', META_UPDATE_FIELD),
    },
    {
        value: '$inc',
        meta: META_UPDATE_FIELD,
        description: 'The $inc operator increments the value of a field by a specified amount.',
        snippet: '{ $inc: { "${1:field}": ${2:value} } }',
        link: getDocLink('$inc', META_UPDATE_FIELD),
    },
    {
        value: '$min',
        meta: META_UPDATE_FIELD,
        description: 'Retrieves the minimum value for a specified field',
        snippet: '{ $min: { "${1:field}": ${2:value} } }',
        link: 'https://learn.microsoft.com/en-us/azure/documentdb/operators/accumulators/$min',
    },
    {
        value: '$max',
        meta: META_UPDATE_FIELD,
        description: 'The $max operator returns the maximum value from a set of input values.',
        snippet: '{ $max: { "${1:field}": ${2:value} } }',
        link: 'https://learn.microsoft.com/en-us/azure/documentdb/operators/accumulators/$max',
    },
    {
        value: '$mul',
        meta: META_UPDATE_FIELD,
        description: 'The $mul operator multiplies the value of a field by a specified number.',
        snippet: '{ $mul: { "${1:field}": ${2:value} } }',
        link: getDocLink('$mul', META_UPDATE_FIELD),
    },
    {
        value: '$rename',
        meta: META_UPDATE_FIELD,
        description: 'The $rename operator allows renaming fields in documents during update operations.',
        snippet: '{ $rename: { "${1:oldField}": "${2:newField}" } }',
        link: getDocLink('$rename', META_UPDATE_FIELD),
    },
    {
        value: '$set',
        meta: META_UPDATE_FIELD,
        description: 'The $set operator in Azure DocumentDB updates or creates a new field with a specified value',
        snippet: '{ $set: { "${1:field}": ${2:value} } }',
        link: 'https://learn.microsoft.com/en-us/azure/documentdb/operators/aggregation/$set',
    },
    {
        value: '$setOnInsert',
        meta: META_UPDATE_FIELD,
        description:
            'The $setOnInsert operator sets field values only when an upsert operation results in an insert of a new document.',
        snippet: '{ $setOnInsert: { "${1:field}": ${2:value} } }',
        link: getDocLink('$setOnInsert', META_UPDATE_FIELD),
    },
    {
        value: '$unset',
        meta: META_UPDATE_FIELD,
        description: 'The $unset stage in the aggregation pipeline is used to remove specified fields from documents.',
        snippet: '{ $unset: { "${1:field}": ${2:value} } }',
        link: 'https://learn.microsoft.com/en-us/azure/documentdb/operators/aggregation/$unset',
    },
];

// ---------------------------------------------------------------------------
// Array Update Operators
// ---------------------------------------------------------------------------

const arrayUpdateOperators: readonly OperatorEntry[] = [
    {
        value: '$',
        meta: META_UPDATE_ARRAY,
        description:
            'The $ positional operator identifies an element in an array to update without explicitly specifying the position of the element in the array.',
        link: getDocLink('$', META_UPDATE_ARRAY),
    },
    {
        value: '$[]',
        meta: META_UPDATE_ARRAY,
        description: 'Positional all operator. Acts as a placeholder to update all elements in an array field.',
    },
    {
        value: '$[identifier]',
        meta: META_UPDATE_ARRAY,
        description:
            'Filtered positional operator. Acts as a placeholder to update elements that match an arrayFilters condition.',
    },
    {
        value: '$addToSet',
        meta: META_UPDATE_ARRAY,
        description:
            "The addToSet operator adds elements to an array if they don't already exist, while ensuring uniqueness of elements within the set.",
        snippet: '{ $addToSet: { "${1:field}": ${2:value} } }',
        link: getDocLink('$addToSet', META_UPDATE_ARRAY),
    },
    {
        value: '$pop',
        meta: META_UPDATE_ARRAY,
        description: 'Removes the first or last element of an array.',
        snippet: '{ $pop: { "${1:field}": ${2:1} } }',
        link: getDocLink('$pop', META_UPDATE_ARRAY),
    },
    {
        value: '$pull',
        meta: META_UPDATE_ARRAY,
        description: 'Removes all instances of a value from an array.',
        snippet: '{ $pull: { "${1:field}": ${2:condition} } }',
        link: getDocLink('$pull', META_UPDATE_ARRAY),
    },
    {
        value: '$push',
        meta: META_UPDATE_ARRAY,
        description: 'The $push operator adds a specified value to an array within a document.',
        snippet: '{ $push: { "${1:field}": ${2:value} } }',
        link: getDocLink('$push', META_UPDATE_ARRAY),
    },
    {
        value: '$pullAll',
        meta: META_UPDATE_ARRAY,
        description: 'The $pullAll operator is used to remove all instances of the specified values from an array.',
        snippet: '{ $pullAll: { "${1:field}": [${2:values}] } }',
        link: getDocLink('$pullAll', META_UPDATE_ARRAY),
    },
    {
        value: '$each',
        meta: META_UPDATE_ARRAY,
        description:
            'The $each operator is used within an `$addToSet`or`$push` operation to add multiple elements to an array field in a single update operation.',
        snippet: '{ $each: [${1:values}] }',
        link: getDocLink('$each', META_UPDATE_ARRAY),
    },
    {
        value: '$position',
        meta: META_UPDATE_ARRAY,
        description:
            'Specifies the position in the array at which the $push operator inserts elements. Used with $each.',
        snippet: '{ $position: ${1:index} }',
    },
    {
        value: '$slice',
        meta: META_UPDATE_ARRAY,
        description: 'The $slice operator returns a subset of an array from any element onwards in the array.',
        snippet: '{ $slice: ${1:number} }',
        link: 'https://learn.microsoft.com/en-us/azure/documentdb/operators/array-expression/$slice',
    },
    {
        value: '$sort',
        meta: META_UPDATE_ARRAY,
        description:
            'The $sort stage in the aggregation pipeline is used to order the documents in the pipeline by a specified field or fields.',
        snippet: '{ $sort: { "${1:field}": ${2:1} } }',
        link: 'https://learn.microsoft.com/en-us/azure/documentdb/operators/aggregation/$sort',
    },
];

// ---------------------------------------------------------------------------
// Bitwise Update Operators
// ---------------------------------------------------------------------------

const bitwiseUpdateOperators: readonly OperatorEntry[] = [
    {
        value: '$bit',
        meta: META_UPDATE_BITWISE,
        description: 'The `$bit` operator is used to perform bitwise operations on integer values.',
        snippet: '{ $bit: { "${1:field}": { "${2:and|or|xor}": ${3:value} } } }',
        link: getDocLink('$bit', META_UPDATE_BITWISE),
    },
];

// ---------------------------------------------------------------------------
// Registration
// ---------------------------------------------------------------------------

registerOperators([...fieldUpdateOperators, ...arrayUpdateOperators, ...bitwiseUpdateOperators]);
