/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

// AUTO-GENERATED — DO NOT EDIT BY HAND
//
// Generated by: npm run generate  (scripts/generate-from-reference.ts)
// Sources:      resources/scraped/operator-reference.md
//               resources/overrides/operator-overrides.md
//               resources/overrides/operator-snippets.md
//
// To change operator data, edit the overrides/snippets files and re-run the generator.

import { getDocLink } from './docLinks';
import { registerOperators } from './getFilteredCompletions';
import { META_WINDOW } from './metaTags';
import { type OperatorEntry } from './types';

// ---------------------------------------------------------------------------
// Window Operators
// ---------------------------------------------------------------------------

const windowOperators: readonly OperatorEntry[] = [
    {
        value: '$sum',
        meta: META_WINDOW,
        description: 'The $sum operator calculates the sum of the values of a field based on a filtering criteria',
        snippet: '{ $sum: "${1:\\$field}" }',
        link: 'https://learn.microsoft.com/en-us/azure/documentdb/operators/accumulators/$sum', // inferred from another category
    },
    {
        value: '$push',
        meta: META_WINDOW,
        description: 'The $push operator adds a specified value to an array within a document.',
        snippet: '{ $push: "${1:\\$field}" }',
        link: 'https://learn.microsoft.com/en-us/azure/documentdb/operators/array-update/$push', // inferred from another category
    },
    {
        value: '$addToSet',
        meta: META_WINDOW,
        description:
            "The addToSet operator adds elements to an array if they don't already exist, while ensuring uniqueness of elements within the set.",
        snippet: '{ $addToSet: "${1:\\$field}" }',
        link: 'https://learn.microsoft.com/en-us/azure/documentdb/operators/array-update/$addtoset', // inferred from another category
    },
    {
        value: '$count',
        meta: META_WINDOW,
        description:
            'The `$count` operator is used to count the number of documents that match a query filtering criteria.',
        snippet: '{ $count: "${1:\\$field}" }',
        link: 'https://learn.microsoft.com/en-us/azure/documentdb/operators/accumulators/$count', // inferred from another category
    },
    {
        value: '$max',
        meta: META_WINDOW,
        description: 'The $max operator returns the maximum value from a set of input values.',
        snippet: '{ $max: "${1:\\$field}" }',
        link: 'https://learn.microsoft.com/en-us/azure/documentdb/operators/accumulators/$max', // inferred from another category
    },
    {
        value: '$min',
        meta: META_WINDOW,
        description: 'Retrieves the minimum value for a specified field',
        snippet: '{ $min: "${1:\\$field}" }',
        link: 'https://learn.microsoft.com/en-us/azure/documentdb/operators/accumulators/$min', // inferred from another category
    },
    {
        value: '$avg',
        meta: META_WINDOW,
        description: 'Computes the average of numeric values for documents in a group, bucket, or window.',
        snippet: '{ $avg: "${1:\\$field}" }',
        link: 'https://learn.microsoft.com/en-us/azure/documentdb/operators/accumulators/$avg', // inferred from another category
    },
    {
        value: '$stdDevPop',
        meta: META_WINDOW,
        description: 'The $stddevpop operator calculates the standard deviation of the specified values',
        snippet: '{ $stdDevPop: "${1:\\$field}" }',
        link: 'https://learn.microsoft.com/en-us/azure/documentdb/operators/accumulators/$stddevpop', // inferred from another category
    },
    {
        value: '$bottom',
        meta: META_WINDOW,
        description:
            "The $bottom operator returns the last document from the query's result set sorted by one or more fields",
        snippet: '{ $bottom: "${1:\\$field}" }',
        link: 'https://learn.microsoft.com/en-us/azure/documentdb/operators/accumulators/$bottom', // inferred from another category
    },
    {
        value: '$bottomN',
        meta: META_WINDOW,
        description: 'The $bottomN operator returns the last N documents from the result sorted by one or more fields',
        snippet: '{ $bottomN: "${1:\\$field}" }',
        link: 'https://learn.microsoft.com/en-us/azure/documentdb/operators/accumulators/$bottomn', // inferred from another category
    },
    {
        value: '$covariancePop',
        meta: META_WINDOW,
        description: 'The $covariancePop operator returns the covariance of two numerical expressions',
        snippet: '{ $covariancePop: "${1:\\$field}" }',
        link: getDocLink('$covariancePop', META_WINDOW),
    },
    {
        value: '$covarianceSamp',
        meta: META_WINDOW,
        description: 'The $covarianceSamp operator returns the covariance of a sample of two numerical expressions',
        snippet: '{ $covarianceSamp: "${1:\\$field}" }',
        link: getDocLink('$covarianceSamp', META_WINDOW),
    },
    {
        value: '$denseRank',
        meta: META_WINDOW,
        description:
            'The $denseRank operator assigns and returns a positional ranking for each document within a partition based on a specified sort order',
        snippet: '{ $denseRank: {} }',
        link: getDocLink('$denseRank', META_WINDOW),
    },
    {
        value: '$derivative',
        meta: META_WINDOW,
        description:
            'The $derivative operator calculates the average rate of change of the value of a field within a specified window.',
        snippet: '{ $derivative: { input: "${1:\\$field}", unit: "${2:hour}" } }',
        link: getDocLink('$derivative', META_WINDOW),
    },
    {
        value: '$documentNumber',
        meta: META_WINDOW,
        description:
            'The $documentNumber operator assigns and returns a position for each document within a partition based on a specified sort order',
        snippet: '{ $documentNumber: {} }',
        link: getDocLink('$documentNumber', META_WINDOW),
    },
    {
        value: '$expMovingAvg',
        meta: META_WINDOW,
        description:
            'The $expMovingAvg operator calculates the moving average of a field based on the specified number of documents to hold the highest weight',
        snippet: '{ $expMovingAvg: { input: "${1:\\$field}", N: ${2:number} } }',
        link: getDocLink('$expMovingAvg', META_WINDOW),
    },
    {
        value: '$first',
        meta: META_WINDOW,
        description: "The $first operator returns the first value in a group according to the group's sorting order.",
        snippet: '{ $first: "${1:\\$field}" }',
        link: 'https://learn.microsoft.com/en-us/azure/documentdb/operators/accumulators/$first', // inferred from another category
    },
    {
        value: '$integral',
        meta: META_WINDOW,
        description:
            'The $integral operator calculates the area under a curve with the specified range of documents forming the adjacent documents for the calculation.',
        snippet: '{ $integral: { input: "${1:\\$field}", unit: "${2:hour}" } }',
        link: getDocLink('$integral', META_WINDOW),
    },
    {
        value: '$last',
        meta: META_WINDOW,
        description: 'The $last operator returns the last document from the result sorted by one or more fields',
        snippet: '{ $last: "${1:\\$field}" }',
        link: 'https://learn.microsoft.com/en-us/azure/documentdb/operators/accumulators/$last', // inferred from another category
    },
    {
        value: '$linearFill',
        meta: META_WINDOW,
        description:
            'The $linearFill operator interpolates missing values in a sequence of documents using linear interpolation.',
        snippet: '{ $linearFill: "${1:\\$field}" }',
        link: getDocLink('$linearFill', META_WINDOW),
    },
    {
        value: '$locf',
        meta: META_WINDOW,
        description:
            'The $locf operator propagates the last observed non-null value forward within a partition in a windowed query.',
        snippet: '{ $locf: "${1:\\$field}" }',
        link: getDocLink('$locf', META_WINDOW),
    },
    {
        value: '$minN',
        meta: META_WINDOW,
        description: 'Retrieves the bottom N values based on a specified filtering criteria',
        snippet: '{ $minN: "${1:\\$field}" }',
        link: 'https://learn.microsoft.com/en-us/azure/documentdb/operators/accumulators/$minn',
    },
    {
        value: '$rank',
        meta: META_WINDOW,
        description: 'The $rank operator ranks documents within a partition based on a specified sort order.',
        snippet: '{ $rank: {} }',
        link: getDocLink('$rank', META_WINDOW),
    },
    {
        value: '$shift',
        meta: META_WINDOW,
        description: 'A window operator that shifts values within a partition and returns the shifted value.',
        snippet: '{ $shift: { output: "${1:\\$field}", by: ${2:1}, default: ${3:null} } }',
        link: getDocLink('$shift', META_WINDOW),
    },
    {
        value: '$stdDevSamp',
        meta: META_WINDOW,
        description:
            'The $stddevsamp operator calculates the standard deviation of a specified sample of values and not the entire population',
        snippet: '{ $stdDevSamp: "${1:\\$field}" }',
        link: 'https://learn.microsoft.com/en-us/azure/documentdb/operators/accumulators/$stddevsamp', // inferred from another category
    },
    {
        value: '$top',
        meta: META_WINDOW,
        description: 'The $top operator returns the first document from the result set sorted by one or more fields',
        snippet: '{ $top: "${1:\\$field}" }',
        link: 'https://learn.microsoft.com/en-us/azure/documentdb/operators/accumulators/$top', // inferred from another category
    },
    {
        value: '$topN',
        meta: META_WINDOW,
        description: 'The $topN operator returns the first N documents from the result sorted by one or more fields',
        snippet: '{ $topN: "${1:\\$field}" }',
        link: 'https://learn.microsoft.com/en-us/azure/documentdb/operators/accumulators/$topn', // inferred from another category
    },
];

// ---------------------------------------------------------------------------
// Registration
// ---------------------------------------------------------------------------

registerOperators([...windowOperators]);
