/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

// GENERATED FILE — do not edit.
// Produced from src/styles/fluentOverrides.scss by scripts/build-styles.mjs.

export const fluentOverridesCss = ":where(.fui-Input,.fui-SearchBox,.fui-Combobox,.fui-Dropdown,.fui-Select,.fui-SpinButton,.fui-Textarea){--colorNeutralForeground3: var(--vscode-descriptionForeground, var(--vscode-foreground));--colorNeutralForeground4: var( --vscode-input-placeholderForeground, var(--vscode-descriptionForeground, var(--vscode-foreground)) );--colorNeutralStroke1: var(--vscode-checkbox-border, var(--vscode-input-border, color-mix(in srgb, var(--vscode-foreground) 55%, transparent)));--colorNeutralStroke1Hover: color-mix(in srgb, var(--vscode-foreground) 45%, var(--vscode-checkbox-border, var(--vscode-input-border, color-mix(in srgb, var(--vscode-foreground) 55%, transparent))));--colorNeutralStroke1Pressed: color-mix(in srgb, var(--vscode-foreground) 45%, var(--vscode-checkbox-border, var(--vscode-input-border, color-mix(in srgb, var(--vscode-foreground) 55%, transparent))));--colorNeutralStrokeAccessible: var(--vscode-checkbox-border, var(--vscode-input-border, color-mix(in srgb, var(--vscode-foreground) 55%, transparent)));--colorNeutralStrokeAccessibleHover: color-mix(in srgb, var(--vscode-foreground) 45%, var(--vscode-checkbox-border, var(--vscode-input-border, color-mix(in srgb, var(--vscode-foreground) 55%, transparent))));--colorNeutralStrokeAccessiblePressed: color-mix(in srgb, var(--vscode-foreground) 45%, var(--vscode-checkbox-border, var(--vscode-input-border, color-mix(in srgb, var(--vscode-foreground) 55%, transparent))))}:where(.fui-ProgressBar){--colorCompoundBrandBackground: var(--vscode-progressBar-background, var(--colorBrandStroke1));--colorNeutralBackground6: color-mix(in srgb, var(--vscode-foreground) 15%, transparent)}:where(.fui-ProgressBar:not([aria-valuenow])){--colorNeutralBackground6: transparent;--colorCompoundBrandBackground: transparent;--colorTransparentBackground: var(--vscode-progressBar-background, var(--colorBrandStroke1))}";
